version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:18.17.0

jobs:
  deploy:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build app
          command: npm run build
      - run:
          name: Install Vercel CLI
          command: npm install -g vercel
      - run:
          name: Deploy to Vercel
          command: |
            vercel --token=$VERCEL_TOKEN --prod --confirm

workflows:
  deploy_on_pr:
    jobs:
      - deploy:
          filters:
            branches:
              ignore: main
